version : '3.3'

volumes:
    uptimekuma:

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - uptimekuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3002:3001
