version: '3.8'

services:
  vsftpd:
    image: panubo/vsftpd
    ports:
      - "2121:21"
    environment:
      FTP_USER: ftpuser   # USER
      FTP_PASSWORD: password  # PASSWORD
      PASV_ADDRESS: 192.168.0.XX  # IP
      PASV_PORT_RANGE: 22000-22010
    volumes:
      - "/../../:/home/vsftpd/ftpuser"    #STORAGE

networks:
  mynetwork:
    driver: bridge
